# Generated by Django 5.1.5 on 2025-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField()),
                ('inicio_semana', models.DateField()),
                ('fin_semana', models.DateField()),
                ('cantidad_registro', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
