# Generated by Django 5.1.5 on 2025-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Cliente')),
                ('rfc', models.CharField(max_length=15, verbose_name='RFC')),
            ],
        ),
    ]
