# Generated by Django 5.1.5 on 2025-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinatarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatariosmodel',
            name='destino',
            field=models.CharField(blank=True, max_length=250, verbose_name='Destino'),
        ),
    ]
